name: Lock Docker Compose Version
description: Download and install a specific version of Docker Compose (v2.36.0)

inputs:
  version:
    description: "Docker Compose version"
    required: false
    default: "v2.36.0"

runs:
  using: composite
  steps: 
    - run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -sSL https://github.com/docker/compose/releases/download/${{ inputs.version }}/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
      shell: bash